### ISSUE TITLE
README.md instructions for Pkg.clone syntax deprecated for Julia v1.2

### ISSUE THREAD

**Issue by rymanderson** [byuflowlab/GeometricTools.jl#1]
I had to do the following to install on Julia v1.2:
```
] # enter Julia's "pkg" manager
add https://github.com/byuflowlab/GeometricTools.jl.git
```

**Comment by EdoAlvarezR** [comment]
The master branch only supports up to Julia v0.7. For v1.x.x, use the branch created by Taylor: https://github.com/byuflowlab/GeometricTools.jl/tree/julia1.0

I've been delaying updating the master to v1.x.x as I also have in my TODO a major rewrite allowing high-performance computing and automatic differentiation. In the meanwhile, you are welcome to merge any new features from the master into the `julia1.0` branch.

Ps: note that FLOWVLM is also in v0.6-v0.7.
